import { createFileRoute } from "@tanstack/react-router";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import ReactMarkdown from "react-markdown";
import { Download, FileText, Printer, Share2 } from "lucide-react";
import { PageShell } from "@/components/shared/page-shell";
import { GlassCard } from "@/components/shared/glass-card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { cashFlow, complianceTrend, execSummary, monthlySpending } from "@/lib/mock-data";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports — Finance AI Copilot" },
      { name: "description", content: "Executive summaries, P&L, cash flow, and audit reports." },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  return (
    <PageShell title="Reports">
      <GlassCard className="p-0">
        <div className="flex items-center justify-between border-b border-border/60 px-6 py-4">
          <div>
            <div className="text-muted-foreground text-xs">Report · July 2026</div>
            <h3 className="text-lg font-semibold">Acme Inc — Financial Overview</h3>
          </div>
          <div className="flex gap-2">
            <Button size="sm" variant="outline"><Share2 className="mr-1 size-4" /> Share</Button>
            <Button size="sm" variant="outline"><Printer className="mr-1 size-4" /> Print</Button>
            <Button size="sm" className="bg-gradient-primary"><Download className="mr-1 size-4" /> Export</Button>
          </div>
        </div>

        <Tabs defaultValue="summary" className="p-6">
          <TabsList className="glass mb-6">
            <TabsTrigger value="summary">Executive Summary</TabsTrigger>
            <TabsTrigger value="pnl">Profit & Loss</TabsTrigger>
            <TabsTrigger value="cash">Cash Flow</TabsTrigger>
            <TabsTrigger value="expense">Expense Analysis</TabsTrigger>
            <TabsTrigger value="audit">Audit Report</TabsTrigger>
          </TabsList>

          <TabsContent value="summary">
            <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
              <div className="prose prose-invert prose-sm max-w-none lg:col-span-2">
                <div className="mb-4 flex items-center gap-2 text-xs text-muted-foreground">
                  <FileText className="size-4" /> Generated by Reporting Agent · 2 min ago
                </div>
                <ReactMarkdown>{execSummary}</ReactMarkdown>
              </div>
              <GlassCard>
                <h4 className="text-sm font-semibold">Compliance trend</h4>
                <div className="mt-3 h-40">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={complianceTrend}>
                      <XAxis dataKey="week" stroke="#71717a" fontSize={10} />
                      <YAxis stroke="#71717a" fontSize={10} domain={[80, 100]} />
                      <Tooltip contentStyle={{ background: "rgba(20,20,25,0.9)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12 }} />
                      <Line type="monotone" dataKey="score" stroke="#22c55e" strokeWidth={2} dot={{ r: 3 }} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </GlassCard>
            </div>
          </TabsContent>

          <TabsContent value="pnl">
            <ChartBlock title="Revenue vs expenses">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlySpending}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                  <XAxis dataKey="month" stroke="#71717a" fontSize={12} />
                  <YAxis stroke="#71717a" fontSize={12} tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`} />
                  <Tooltip contentStyle={{ background: "rgba(20,20,25,0.9)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12 }} />
                  <Bar dataKey="spend" fill="#6366f1" radius={[8, 8, 0, 0]} />
                  <Bar dataKey="budget" fill="#a855f7" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </ChartBlock>
          </TabsContent>

          <TabsContent value="cash">
            <ChartBlock title="Cash flow (inflow vs outflow)">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={cashFlow}>
                  <defs>
                    <linearGradient id="in" x1="0" x2="0" y1="0" y2="1">
                      <stop offset="0%" stopColor="#22c55e" stopOpacity={0.6} />
                      <stop offset="100%" stopColor="#22c55e" stopOpacity={0} />
                    </linearGradient>
                    <linearGradient id="out" x1="0" x2="0" y1="0" y2="1">
                      <stop offset="0%" stopColor="#ef4444" stopOpacity={0.5} />
                      <stop offset="100%" stopColor="#ef4444" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                  <XAxis dataKey="month" stroke="#71717a" fontSize={12} />
                  <YAxis stroke="#71717a" fontSize={12} tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`} />
                  <Tooltip contentStyle={{ background: "rgba(20,20,25,0.9)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12 }} />
                  <Area type="monotone" dataKey="inflow" stroke="#22c55e" fill="url(#in)" strokeWidth={2} />
                  <Area type="monotone" dataKey="outflow" stroke="#ef4444" fill="url(#out)" strokeWidth={2} />
                </AreaChart>
              </ResponsiveContainer>
            </ChartBlock>
          </TabsContent>

          <TabsContent value="expense">
            <ChartBlock title="Monthly spending trend">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={monthlySpending}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                  <XAxis dataKey="month" stroke="#71717a" fontSize={12} />
                  <YAxis stroke="#71717a" fontSize={12} tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`} />
                  <Tooltip contentStyle={{ background: "rgba(20,20,25,0.9)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12 }} />
                  <Line type="monotone" dataKey="spend" stroke="#38bdf8" strokeWidth={3} dot={{ r: 4 }} />
                </LineChart>
              </ResponsiveContainer>
            </ChartBlock>
          </TabsContent>

          <TabsContent value="audit">
            <div className="text-muted-foreground text-sm">
              128 invoices audited · 7 exceptions · 0 critical findings. Compliance score 97.2%.
              Detailed audit trail is available under <a className="text-primary underline" href="/audit">Audit Logs</a>.
            </div>
          </TabsContent>
        </Tabs>
      </GlassCard>
    </PageShell>
  );
}

function ChartBlock({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <GlassCard>
      <h4 className="text-sm font-semibold">{title}</h4>
      <div className="mt-4 h-80">{children}</div>
    </GlassCard>
  );
}
